### ISSUE TITLE
SP107E support

### ISSUE THREAD

**Issue by and7ey** [roslovets/SP110E#3]
Many thanks for your work!

Should your lib work with SP107E? Believe, it should be quite similar to SP110E.
SP107E is controlled with LED Chord application. Here are some photos - https://mysku.club/blog/aliexpress/77266.html:

![](https://pic.mysku-st.net/uploads/pictures/00/13/89/2019/11/30/244c57.jpg)

The following code taken from the Bleak page returns nothing (I test from Mac).
```
import asyncio
from bleak import BleakScanner

async def main():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d)

asyncio.run(main())
```

But nRF connect apps installed on my android phone sees the device.

**Comment by roslovets** [comment]
> Should your lib work with SP107E?

No, it should not. SP107E may have a completely different BLE protocol. You might need to apply reverse engineering do discover this.
It's strange that the bleak cannot find your device, because it's a general BLE library. Make sure that another app is not holding the connection.

**Comment by and7ey** [comment]
Here is the working HA component both for SP107E and SP110E based on official Home Assistant BT integration
https://github.com/monty68/uniled
